### ISSUE TITLE
Shuffling password invalidates password stored in DB

### ISSUE THREAD

**Issue by i-am-chitti** [Souptik2001/wordpress.setup#1] opened 2022-05-10 13:20 UTC
`wp config shuffle-salts` runs on every start which generates new salts. But this also invalidates all previous password stored in database (as hashes has changed) and left user no option to login with their last remembered password. So, we should not be generating new salts everytime lando starts.

**Comment by Souptik2001** [comment] 2022-05-10 18:19
@i-am-chitti Yes exactly😱!!

_Checking for solution...._

**Comment by Souptik2001** [comment] 2022-05-11 12:56
@i-am-chitti Fixed it with a minor issue. Check the PR's comment.👆

The issue is still not completely resolved so let it be open.

**Comment by Souptik2001** [comment] 2022-10-22 15:04
Closing as solved.

**Closed as completed by Souptik2001** 2022-10-22 15:04 UTC
